apiVersion: v1
kind: ConfigMap
metadata:
  name: prodvistaui-configmap
  namespace: agys-v1 
data:
  VITE_API_TIMEOUT: "30000"
  VITE_APP_TITLE: "ProdVista Dashboard"
  VITE_AZURE_TENANT_ID: "common"
  VITE_ENABLE_DEVTOOLS: "false"
  VITE_REDIRECT_URI: "https://aks-v1-dev.hospitalityrevolution.com"
  VITE_API_URL: ""
  VITE_API_BASE_PATH: "/prodvista/api"